-- Drop and recreate Users table (Example)

DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);


DROP TABLE IF EXISTS postings CASCADE;
CREATE TABLE postings (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  price SMALLINT,
  condition VARCHAR(255),
  sold BOOLEAN NOT NULL DEFAULT FALSE,

  seller_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  photo_url VARCHAR(255) NOT NULL
);


DROP TABLE IF EXISTS conversations CASCADE;
CREATE TABLE conversations (
  id SERIAL PRIMARY KEY NOT NULL,
  time TIMESTAMP,
  message_content TEXT,
  posting_id INTEGER REFERENCES postings(id) ON DELETE CASCADE,

  sender_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  recipient_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
);


DROP TABLE IF EXISTS favourites CASCADE;
CREATE TABLE favourites (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  posting_id INTEGER REFERENCES postings(id) ON DELETE CASCADE
);
